### ISSUE TITLE
babel-traverse critical vulnerability

### ISSUE THREAD

**Issue by crisward** [pugjs/then-jade#24]
babel-traverse critical vulnerability reported.

https://github.com/advisories/GHSA-67hx-6x53-jw92

This requires

```
var babelTemplate  = require('babel-template');
```

To be updated to 

```
var { default: babelTemplate } = require('@babel/template');
```

However if I do that, the tests fail with

```
test cases for then-pug specific features › gn for loop

    /test/cases-then-pug/gn-for-loop.pug:2:3

    Unbuffered code structure could not be parsed; Error: No substitution given for "_". If this is not meant to be a
                placeholder you may want to consider passing one of the following options to @babel/template:
                - { placeholderPattern: false, placeholderWhitelist: new Set(['_'])}
                - { placeholderPattern: /^_$/ } in var dirs = yield readdir('cases-then-pug/samples')
```

Looks like this is caused by a change to the way `babelTemplate` works. 

Way out of my depth with this. Anyone else have any idea how to fix this???

**Comment by crisward** [comment]
I use it as part of my companies cms system (www.duodesign.co.uk). We used then-jade a long time ago and during a rewrite then pug was an obvious successor. We need async templating for specific features. I've forked it due to the necessity to patch various dependency issues.

We're a small UK based web agency and then-pug produces pages for quite a few websites.

**Comment by crisward** [comment]
Thanks for the background. I was expecting to have to dig through babel changelogs to attempt an update, so any help is appreciated. 

We precompile to js all our templates so the compile step also isn’t an issue for us.

**Comment by jeromew** [comment]
I pushed a commit that upgrades the babel dependency to 7.24.4 ; you can see in the diff what I changed for babel-template

they now have 2 ways of declaring placeholder variables and they apparently changed their default regexp for detecting placeholder names.

`then-pug` is using a construct like `_ = function*{  ...buffered code }` to catch the js code that is in the pug template and the recent babel-template version was wrongly detecting `_` as a placeholder when it is in fact just a dummy variable that was used to create a dummy statement (used to make babel-template happy if I remember well)

I switched to their new syntacticPlaceholders to avoid the problem.

can you confirm that this fixes your problem ?

**Comment by crisward** [comment]
Thanks for this. I'll give it a go.

**Comment by crisward** [comment]
That's done the trick. Many thanks!
